name: Build OpenWrt for BPI-R4

on:
  push:
    branches:
      - main # Запускать при пуше в ветку main
  workflow_dispatch: # Позволяет запускать вручную из вкладки "Actions"

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu в качестве виртуальной машины (обычно 4 ядра CPU, 7GB RAM)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Скачиваем ваш репозиторий

      - name: Show System Information
        run: |
          echo "Disk space:"
          df -h
          echo "CPU Cores:"
          nproc

      - name: Set up build environment
        run: |
          echo "Installing essential build dependencies..."
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget \
            libtraceevent-dev systemtap-sdt-dev libslang-dev
          echo "Dependencies installed."

      - name: Run OpenWrt Build Script
        run: |
          echo "Making build script executable..."
          chmod +x bpi-r4-openwrt-builder.sh

          echo "Starting OpenWrt build process with your script..."
          ./bpi-r4-openwrt-builder.sh

          echo "Build script finished. Checking for compiled firmware..."

      - name: Find and Upload Compiled Firmware
        uses: actions/upload-artifact@v4 # Загружаем скомпилированную прошивку как артефакт
        with:
          name: OpenWrt-Firmware_R-4
          # ВАЖНО: Укажите здесь ПРАВИЛЬНЫЙ путь к папке, где ваш скрипт сохраняет готовую прошивку.
          # Это САМАЯ частая причина проблем.
          # Например, если скрипт клонирует OpenWrt SDK в папку 'openwrt'
          # и затем компилирует, то прошивка может быть в 'openwrt/bin/targets/mediatek/filogic/'
          # Или если скрипт сам создает папку 'output/', то путь будет './output/'.
          path: openwrt/bin/targets/mediatek/filogic/ # <--- ЭТОТ ПУТЬ СКОРЕЕ ВСЕГО НУЖНО ИЗМЕНИТЬ!
          # Вы можете посмотреть логи вашего скрипта `./bpi-r4-openwrt-builder.sh`
          # чтобы узнать точный путь к скомпилированным файлам.
